from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from kokoro import KPipeline
import soundfile as sf
import io
import base64
import numpy as np

app = FastAPI()

# Load the model once at startup
print("Loading Kokoro-82M model...")
# Initialize pipeline (lang_code 'a' for American English)
pipeline = KPipeline(lang_code='a')
print("Model loaded successfully.")

class SynthesizeRequest(BaseModel):
    text: str
    voice: str = "af_heart" # Clear, natural female voice

@app.get("/health")
async def health():
    return {"status": "ok"}

@app.post("/synthesize")
async def synthesize(req: SynthesizeRequest):
    if not req.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty")
        
    try:
        # Generate audio. The pipeline yields chunks of (graphemes, phonemes, audio)
        generator = pipeline(req.text, voice=req.voice)
        
        all_audio = []
        for _, _, audio in generator:
            all_audio.append(audio)
            
        if not all_audio:
            raise HTTPException(status_code=500, detail="No audio generated by Kokoro")
            
        # Concatenate chunks if there are multiple (e.g. for long sentences)
        final_audio = np.concatenate(all_audio)
        
        # Write to in-memory WAV buffer
        buffer = io.BytesIO()
        sf.write(buffer, final_audio, 24000, format='WAV')
        buffer.seek(0)
        
        # Base64 encode
        b64_audio = base64.b64encode(buffer.read()).decode('utf-8')
        
        return {
            "audio": b64_audio,
            "contentType": "audio/wav"
        }
    except Exception as e:
        print(f"Error synthesizing audio: {e}")
        raise HTTPException(status_code=500, detail=str(e))
